#!/bin/bash
mvn clean install
#cd target/releases/collection-sort-1.0-SNAPSHOT
#tar -zxf ./collection-sort-1.0-SNAPSHOT.jar
#rm collection-sort-1.0-SNAPSHOT.jar
#cd ..
rm -rf ~/Developer/elasticsearch-6.3.2/plugins/collection-sort
mv target/releases/collection-sort-1.0-SNAPSHOT/collection-sort ~/Developer/elasticsearch-6.3.2/plugins/collection-sort
~/Developer/elasticsearch-6.3.2/bin/elasticsearch
